Questions + visu
vitalab/deep-learning-tutorials pull request #8
Opened 2021-04-16 14:24 UTC by jodoin

2021-04-16 15:05 UTC, nathanpainchaud requested changes
Minor typos + font recommendations. Only one question that I recommend to phrase a bit differently.

@jodoin I also want to rework the single latent vector visualization for MNIST, but I'll do it once the changes are applied to avoid conflicts.

2021-04-16 15:05 UTC, nathanpainchaud commented on tutorials/mnist-autoencoders.ipynb
> +    "* In the previous cell, we use for our VAE the same encoder and decoder function than for the AE.  The only difference is the output of the encoder is multiplied by 2.  Why do you think that is?
I'd suggest wording this a bit differently (to emphasize the functions built the networks' architectures):
```suggestion
    "* In the previous cell, we used the same function to build our VAE's encoder and decoder networks than the AE.  The only difference is the output size of the encoder is multiplied by 2.  Why do you think that is?\n",
```

2021-04-16 15:22 UTC, nathanpainchaud commented on tutorials/cardiac-mri-autoencoders.ipynb
> +    "* How many **parameters** does this encoder network has?\n",
Typo.
```suggestion
    "* How many **parameters** does this encoder network have?\n",
```

2021-04-16 15:36 UTC, nathanpainchaud approved these changes

2021-04-16 21:52 UTC, nathanpainchaud requested changes
Small typos and a few questions.

2021-04-16 21:52 UTC, nathanpainchaud commented on tutorials/mnist-autoencoders.ipynb
> +    "* https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html\n",
Use links syntax:
```suggestion
    "* [Deep Learning With PyTorch: A 60 Minute Blitz](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html)\n",
    "* [Training a Classifier on CIFAR10](https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html)\n",
```

2021-04-16 21:52 UTC, nathanpainchaud commented on tutorials/mnist-autoencoders.ipynb
> +    "before coding autoencoders.  Unfortunately, with the time being, you might not have enough time to go through these tutorials.\n",
Phrasing.
```suggestion
    "before coding autoencoders.  Unfortunately, you might not have enough time to go through these tutorials during the hands-on limited time.\n",
```

2021-04-16 21:52 UTC, nathanpainchaud commented on tutorials/mnist-autoencoders.ipynb
> +    "We thus suggest you to start playing around with these two autoencoder notebooks, tweak with some hyperparameters, retrain the networks, and ask questions if you have some.\n",
Phrasing.
```suggestion
    "We thus suggest you to start playing around with these two autoencoder notebooks, tweak with some hyperparameters, retrain the networks, and ask questions if you have any.\n",
```

2021-04-16 21:52 UTC, nathanpainchaud commented on tutorials/mnist-autoencoders.ipynb
> +    "Please note that *mnist_train* and *mnist_test* are PyTorch **datasets**.  A dataset is an object that encapsulates data in the form of PyTorch tensors.  You may get access (and visualize) the d
Font.
```suggestion
    "Please note that `mnist_train` and `mnist_test` are PyTorch **datasets**.  A dataset is an object that encapsulates data in the form of PyTorch tensors.  You may get access (and visualize) the data with the following code."
```

2021-04-16 21:52 UTC, nathanpainchaud commented on tutorials/mnist-autoencoders.ipynb
> +    "# What is mnist_train and mnist_test?  Lets look at it\n",
Typos.
```suggestion
    "# What are `mnist_train` and `mnist_test`?  Let's look at them\n",
```

2021-04-16 21:52 UTC, nathanpainchaud commented on tutorials/mnist-autoencoders.ipynb
> +    "The previous `train(...)` function contains a typical **PyTorch training loop**.  That training loop contains a **forward pass**, a **backward pass**, a **gradient step** (*optimizer.step()*) an
Font.
```suggestion
    "The previous `train(...)` function contains a typical **PyTorch training loop**.  That training loop contains a **forward pass**, a **backward pass**, a **gradient step** (`optimizer.step()`) and a **validation check**.  Also, common to PyTorch are **data loaders**.  A data loader is an object that encapsulates a dataset and provides an iterable over its content.\n",
```

2021-04-16 21:52 UTC, nathanpainchaud commented on tutorials/mnist-autoencoders.ipynb
>      "* Do you see what the data loaders are used for?\n",
This question seems less relevant to me since you now explain what data loaders are in the paragraph just above. Do you still think it is useful?

2021-04-16 21:52 UTC, nathanpainchaud commented on tutorials/mnist-autoencoders.ipynb
> +  },
I'd move this cell below the cell that does the latent space visualization itself (the next one).

2021-04-16 21:52 UTC, nathanpainchaud commented on tutorials/mnist-autoencoders.ipynb
> +    "### See the difference between this latent space and that of the previous auto-encoder?"
Typo.
```suggestion
    "### See the difference between this latent space and that of the previous autoencoder?"
```

2021-04-16 21:52 UTC, nathanpainchaud commented on tutorials/mnist-autoencoders.ipynb
> +    "# Run this cell only if the auto-encoder has a latent space size of 2.\n",
Typo.
```suggestion
    "# Run this cell only if the autoencoder has a latent space size of 2.\n",
```

2021-04-16 21:52 UTC, nathanpainchaud commented on tutorials/mnist-autoencoders.ipynb
> +    "Before we move on to the variational auto-encoder, go back to the beginning of this notebook and replace the 32 latent space size by a size of 2 and retrain the autoencoder.\n",
Typo.
```suggestion
    "Before we move on to the variational autoencoder, go back to the beginning of this notebook and replace the 32 latent space size by a size of 2 and retrain the autoencoder.\n",
```

2021-04-17 13:07 UTC, jodoin commented on tutorials/mnist-autoencoders.ipynb
>      "* Do you see what the data loaders are used for?\n",
Data loader seams to be a big deal.  That is why.

2021-04-17 13:13 UTC, merged